spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/game_data
    username: root
    password: admin
  jpa:
    show-sql: true
    defer-datasource-initialization: true